blank_issues_enabled: false
contact_links:
  - name: TinyUF2 Discussion
    url: https://github.com/adafruit/tinyuf2/discussions
    about: If you have other questions or need help, post it here.
